FROM grafana/grafana:latest

# Install SQLite plugin for direct database access
USER root
RUN grafana-cli plugins install frser-sqlite-datasource

# Copy Grafana provisioning files
COPY deploy/grafana/provisioning /etc/grafana/provisioning

# Set permissions
RUN chown -R grafana:grafana /etc/grafana/provisioning

USER grafana

# Expose Grafana port
EXPOSE 3000
